---
bobcatUrl: &bobcat-url
  "{{{ bobcatUrl }}}"
getitUrl: &getit-url
  "{{{ getitUrl }}}"
guidesUrl: &guides-url
  "{{{ guidesUrl }}}"

default-tabs: &default-tabs
  articles:
    label: Articles & Databases
    title: Search databases for articles or browse databases by subject
    alt: Search databases for articles or browse databases by subject
    href: http://guides.nyu.edu/arch
    target: _blank
  books:
    engine: primo
    label: Books & More
    title: Search NYU's catalog for books, journals, scripts, scores, archival
      materials, NYU dissertations, videos, sound recordings
    alt: Search NYU's catalog for books, journals, scripts, scores, archival materials,
      NYU dissertations, videos, sound recordings
  journals:
    engine: getit
    label: Journals
    title: Search for journals by title or for articles by citation
    alt: Search for journals by title or for articles by citation
  reserves:
    engine: primo
    label: Course Reserves
    title: Search for library materials that are held at one location for a particular course
    alt: Search for library materials that are held at one location for a particular course

default-getit-search-values: &default-getit-search-values
  getitUrl: *getit-url
  searchTypes:
  - label: contains
    value: contains
  - label: begins with
    value: begins
  - label: exact match
    value: exact

default-guide-search-values: &default-guide-search-values
  guides:
    guidesUrl: *guides-url

environments:
  production:
    mustache: ./mustache.production.yml
  staging:
    mustache: ./mustache.staging.yml
  development:
    mustache: ./mustache.staging.yml
institutions:
  NYU:
    tabsList:
    - books
    - articles
    - journals
    - reserves
    tabs: *default-tabs
    tabLinks:
      books:
      - label: Advanced search
        href: "{{{ bobcatUrl }}}/primo-explore/search?vid=NYU&mode=advanced"
      journals:
      - label: Advanced search
        href: "{{{ getitUrl }}}"
      reserves:
      - label: Advanced search
        href: "{{{ bobcatUrl }}}/primo-explore/search?tab=reserves&search_scope=bobstcr&vid=NYU&mode=advanced"
    engineValues:
      primo:
        books:
          institution: NYU
          bobcatUrl: *bobcat-url
          vid: NYU
          scope: all
          tab: all
        reserves:
          institution: NYU
          bobcatUrl: *bobcat-url
          vid: NYU
          scope: bobstcr
          tab: reserves
      getit:
        journals:
          <<: *default-getit-search-values
          institution: NYU
  NYUAD:
    tabsList:
    - books
    - articles
    - journals
    - reserves
    - guides
    - accounts
    tabs:
      <<: *default-tabs
      articles:
        label: Articles & Databases
        title: Search databases for articles or browse databases by subject
        alt: Search databases for articles or browse databases by subject
        href: http://guides.nyu.edu/adarch
        target: _blank
      guides:
        label: Subject Guides
        title: Subject Guides
        alt: Subject Guides
        engine: guides
      accounts:
        label: My Accounts
        title: My Accounts
        alt: My Accounts
    tabLinks:
      books:
      - label: Advanced search
        href: "{{{ bobcatUrl }}}/primo-explore/search?vid=NYUAD&mode=advanced"
      journals:
      - label: Advanced search
        href: "{{{ getitUrl }}}/?&umlaut.institution=NYUAD"
      reserves:
      - label: Advanced search
        href: "{{{ bobcatUrl }}}/primo-explore/search?tab=nyuadcr&search_scope=nyuadcr&vid=NYUAD&mode=advanced"
      guides:
      - label: All Subject Guides
        href: https://guides.nyu.edu/
      - label: Abu Dhabi Library Guides
        href: https://guides.nyu.edu/abudhabi
      accounts:
      - label: Interlibrary Loan
        href: https://ill.library.nyu.edu/
      - label: Library Account
        href: https://eshelf.library.nyu.edu/account
    engineValues:
      primo:
        books:
          institution: NYUAD
          bobcatUrl: *bobcat-url
          vid: NYUAD
          scope: all
          tab: all
        reserves:
          institution: NYUAD
          bobcatUrl: *bobcat-url
          vid: NYUAD
          scope: nyuadcr
          tab: nyuadcr
      getit:
        journals:
          <<: *default-getit-search-values
          institution: NYUAD
      guides:
        <<: *default-guide-search-values
  NYUSH:
    tabsList:
    - books
    - articles
    - journals
    - reserves
    - guides
    - accounts
    tabs:
      <<: *default-tabs
      guides:
        label: Subject Guides
        title: Subject Guides
        alt: Subject Guides
        engine: guides
      accounts:
        label: My Accounts
        title: My Accounts
        alt: My Accounts
    tabLinks:
      books:
      - label: Advanced search
        href: "{{{ bobcatUrl }}}/primo-explore/search?vid=NYUSH&mode=advanced"
      journals:
      - label: Advanced search
        href: "{{{ getitUrl }}}/?&umlaut.institution=NYUSH"
      reserves:
      - label: Advanced search
        href: "{{{ bobcatUrl }}}/primo-explore/search?tab=nyushcr&search_scope=nyushcr&vid=NYUSH&mode=advanced"
      guides:
      - label: All Subject Guides
        href: https://guides.nyu.edu/
      - label: Shanghai Library Guides
        href: https://guides.nyu.edu/?group_id=5748
      accounts:
      - label: Interlibrary Loan
        href: https://ill.library.nyu.edu/
      - label: Library Account
        href: https://eshelf.library.nyu.edu/account
    engineValues:
      primo:
        books:
          institution: NYUSH
          bobcatUrl: *bobcat-url
          vid: NYUSH
          scope: all
          tab: all
        reserves:
          institution: NYUSH
          bobcatUrl: *bobcat-url
          vid: NYUSH
          scope: nyushcr
          tab: nyushcr
      getit:
        journals:
          <<: *default-getit-search-values
          institution: NYUSH
      guides:
        <<: *default-guide-search-values
