---
# Tab Info
bobcat-books: &bobcat-books
  label: Catalog Search
  title: Search NYU's catalog for books, journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings
ares-reserves: &ares-reserves
  label: Course Reserves
  title: Search for library materials that are held at one location for a particular course
  open:
    href: https://ares.library.nyu.edu/
    target: _blank
subject-guides: &subject-guides
  label: Subject Guides
  title: Subject Guides
guides-articles: &guides-articles
  label: Articles & Databases
  title: Search databases for articles or browse databases by subject
  open:
    href: http://guides.nyu.edu/arch
    target: _blank
my-accounts: &my-accounts
  label: My Accounts
  title: My Accounts

# Engines
guides-engine: &guides-engine
  type: guides
  guidesUrl: https://guides.nyu.edu

institutions:
  NYU:
  - <<: *bobcat-books
    engine:
      type: primo
      institution: NYU
      bobcatUrl: "https://search.library.nyu.edu"
      vid: 01NYU_INST:NYU
      scope: CI_NYU_CONSORTIA
      tab: Unified_Slot
    more:
    - <a href="https://search.library.nyu.edu/discovery/search?vid=01NYU_INST:NYU&lang=en&mode=advanced" target="_blank">Advanced search</a>
    - Need the full text of an article? <a href="https://search.library.nyu.edu/discovery/citationlinker?vid=01NYU_INST:NYU" target="_blank">Use the search by citation tool</a>.
  - <<: *guides-articles
  - <<: *ares-reserves
  NYUAD:
  - <<: *bobcat-books
    engine:
      type: primo
      institution: NYUAD
      bobcatUrl: "https://search.abudhabi.library.nyu.edu"
      vid: 01NYU_AD:AD
      scope: CI_NYUAD_NYU
      tab: default_slot
    more:
    - <a href="https://search.abudhabi.library.nyu.edu/discovery/search?vid=01NYU_AD:AD&mode=advanced" target="_blank">Advanced search</a>
    - Need the full text of an article? <a href="https://search.abudhabi.library.nyu.edu/discovery/citationlinker?vid=01NYU_AD:AD" target="_blank">Use the search by citation tool</a>.
  - label: Articles & Databases
    title: Search databases for articles or browse databases by subject
    open:
      href: http://guides.nyu.edu/adarch
      target: _blank
  - label: Course Reserves
    title: Search for library materials that are held at one location for a particular course
    engine:
      type: primo
      institution: NYUAD
      bobcatUrl: "https://search.abudhabi.library.nyu.edu"
      vid: 01NYU_AD:AD
      scope: CourseReserves
      tab: default_slot
    more:
    - <a href="https://search.abudhabi.library.nyu.edu/discovery/search?vid=01NYU_AD:AD&mode=advanced" target="_blank">Advanced search</a>
    - Need the full text of an article? <a href="https://search.abudhabi.library.nyu.edu/discovery/citationlinker?vid=01NYU_AD:AD" target="_blank">Use the search by citation tool</a>.
  - <<: *subject-guides
    engine:
      <<: *guides-engine
      placeholder: Enter Search Words (e.g. Company research)
    more:
    - <a href="https://guides.nyu.edu/" target="_blank">All Subject Guides</a>
    - <a href="https://guides.nyu.edu/abudhabi" target="_blank">Abu Dhabi Library Guides</a>
    - Need the full text of an article? <a href="https://search.abudhabi.library.nyu.edu/discovery/citationlinker?vid=01NYU_AD:AD" target="_blank">Use the search by citation tool</a>.
  - <<: *my-accounts
    more:
    - <a href="https://ill.library.nyu.edu/" target="_blank">Interlibrary Loan</a>
    - <a href="https://search.abudhabi.library.nyu.edu/discovery/account?vid=01NYU_AD:AD&section=overview" target="_blank">Library Account</a>
    - Need the full text of an article? <a href="https://search.abudhabi.library.nyu.edu/discovery/citationlinker?vid=01NYU_AD:AD" target="_blank">Use the search by citation tool</a>.
  NYUSH:
  - <<: *bobcat-books
    engine:
      type: primo
      institution: NYUSH
      bobcatUrl: "https://search.shanghai.library.nyu.edu"
      vid: 01NYU_US:SH
      scope: CI_NYUSH
      tab: default_slot
    more:
    - <a href="https://search.shanghai.library.nyu.edu/discovery/search?vid=01NYU_US:SH&mode=advanced" target="_blank">Advanced search</a>
    - Need the full text of an article? <a href="https://search.shanghai.library.nyu.edu/discovery/citationlinker?vid=01NYU_US:SH" target="_blank">Use the search by citation tool</a>.
  - <<: *guides-articles
  - <<: *ares-reserves
  - <<: *subject-guides
    engine:
      <<: *guides-engine
      placeholder: Enter Search Words (e.g. "learning Chinese")
    more:
    - <a href="https://guides.nyu.edu/" target="_blank">All Subject Guides</a>
    - <a href="https://guides.nyu.edu/?group_id=5748" target="_blank">Shanghai Library Guides</a>
    - Need the full text of an article? <a href="https://search.abudhabi.library.nyu.edu/discovery/citationlinker?vid=01NYU_US:SH" target="_blank">Use the search by citation tool</a>.
  - <<: *my-accounts
    more:
    - <a href="https://ill.library.nyu.edu/" target="_blank">Interlibrary Loan</a>
    - <a href="https://search.abudhabi.library.nyu.edu/discovery/account?vid=01NYU_US:SH&section=overview" target="_blank">Library Account</a>
    - Need the full text of an article? <a href="https://search.abudhabi.library.nyu.edu/discovery/citationlinker?vid=01NYU_US:SH" target="_blank">Use the search by citation tool</a>.
  CU:
  - label: Catalog Search
    title: Books & e-books, journals & e-journals, videos, and other materials in the Cooper Union Libraries, NYU libraries, and other participating libraries
    engine:
      type: primo
      institution: CU
      bobcatUrl: "https://search.library.cooper.edu"
      vid: 01NYU_CU:CU
      scope: MyInst_and_CI
      tab: CentralIndex
    more:
      - <a href="https://search.library.cooper.edu/discovery/search?vid=01NYU_CU:CU&mode=advanced" target="_blank">Advanced search</a>
  - label: Databases
    title: Find the best library databases for your research.
    open:
      href: https://library.cooper.edu/az.php
      target: _blank
  - label: E-Journals
    title: Browse e-journals available at Cooper Union by title or search for a specific article
    open:
      href: https://search.library.cooper.edu/discovery/jsearch?vid=01NYU_CU:CU
      target: _blank
  - label: Course Reserves
    title: Search course reserves at Cooper Union by instructor, course name or number, author, title, and other terms
    engine:
      type: primo
      institution: CU
      bobcatUrl: "https://search.library.cooper.edu"
      vid: 01NYU_CU:CU
      scope: CourseReserves
      tab: CourseReserves
    more:
      - <a href="https://search.library.cooper.edu/discovery/search?vid=01NYU_CU:CU&mode=advanced" target="_blank">Advanced search</a>
  NYU_HOME:
    - <<: *bobcat-books
      open:
        href: "https://search.library.nyu.edu/discovery/search?vid=01NYU_INST:NYU"
        target: _blank
      engine:
        type: primo
        institution: NYU
        bobcatUrl: "https://search.library.nyu.edu"
        vid: 01NYU_INST:NYU
        scope: CI_NYU_CONSORTIA
        tab: Unified_Slot
      more:
      - <a href="https://search.library.nyu.edu/discovery/search?vid=01NYU_INST:NYU&mode=advanced" target="_blank">Advanced search</a>
      - <a href="https://search.library.nyu.edu/discovery/citationlinker?vid=01NYU_INST:NYU" target="_blank">For full text articles use the search by citation tool</a>
      - <a href="https://search.library.nyu.edu/discovery/account?vid=01NYU_INST:NYU&section=overview" target="_blank" class="external-link">My Library Account</a>
    - <<: *guides-articles
    - <<: *ares-reserves
