---
articles: &guides-articles
  label: Articles & Databases
  title: Search databases for articles or browse databases by subject
  open:
    href: http://guides.nyu.edu/arch
    target: _blank
books: &bobcat-books
  label: Books & More
  title: Search NYU's catalog for books, journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings
guides: &subject-guides
  label: Subject Guides
  title: Subject Guides
accounts: &my-accounts
  label: My Accounts
  title: My Accounts

ares-reserves: &ares-reserves
  label: Course Reserves
  title: Search for library materials that are held at one location for a particular course
  open:
    href: https://ares.library.nyu.edu/
    target: _blank

guides-engine: &guides-engine
  type: guides
  guidesUrl: https://guides.nyu.edu

environments:
  production:
    bobcatUrl: http://bobcat.library.nyu.edu
  staging:
    bobcatUrl: http://bobcatdev.library.nyu.edu
  development:
    bobcatUrl: http://bobcatdev.library.nyu.edu

institutions:
  NYU:
  - key: books
    <<: *bobcat-books
    engine:
      type: primo
      institution: NYU
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYU
      scope: all
      tab: all
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?vid=NYU&mode=advanced"
  - key: articles
    <<: *guides-articles
  - key: reserves
    <<: *ares-reserves
  NYUAD:
  - key: books
    <<: *bobcat-books
    engine:
      type: primo
      institution: NYUAD
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYUAD
      scope: all
      tab: all
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?vid=NYUAD&mode=advanced"
  - key: articles
    label: Articles & Databases
    title: Search databases for articles or browse databases by subject
    open:
      href: http://guides.nyu.edu/adarch
      target: _blank
  - key: reserves
    label: Course Reserves
    title: Search for library materials that are held at one location for a particular course
    engine:
      type: primo
      institution: NYUAD
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYUAD
      scope: nyuadcr
      tab: nyuadcr
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?tab=nyuadcr&search_scope=nyuadcr&vid=NYUAD&mode=advanced"
  - key: guides
    <<: *subject-guides
    engine:
      <<: *guides-engine
      placeholder: Enter Search Words (e.g. Company research)
    links:
    - label: All Subject Guides
      href: https://guides.nyu.edu/
    - label: Abu Dhabi Library Guides
      href: https://guides.nyu.edu/abudhabi
  - key: accounts
    <<: *my-accounts
    links:
    - label: Interlibrary Loan
      href: https://ill.library.nyu.edu/
    - label: Library Account
      href: https://eshelf.library.nyu.edu/account
  NYUSH:
  - key: books
    <<: *bobcat-books
    engine:
      type: primo
      institution: NYUSH
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYUSH
      scope: nyush
      tab: all
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?vid=NYUSH&mode=advanced"
  - key: articles
    <<: *guides-articles
  - key: reserves
    <<: *ares-reserves
  - key: guides
    <<: *subject-guides
    engine:
      <<: *guides-engine
      placeholder: Enter Search Words (e.g. "learning Chinese")
    links:
    - label: All Subject Guides
      href: https://guides.nyu.edu/
    - label: Shanghai Library Guides
      href: https://guides.nyu.edu/?group_id=5748
  - key: accounts
    <<: *my-accounts
    links:
    - label: Interlibrary Loan
      href: https://ill.library.nyu.edu/
    - label: Library Account
      href: https://eshelf.library.nyu.edu/account
  CU:
  - key: primo-consortium
    label: Consortium Catalog
    title: Books & e-books, journals & e-journals, scripts, scores, archival materials, videos, sound recordings, and other materials in the Consortium libraries
    engine:
      type: primo
      institution: CU
      bobcatUrl: "{{ bobcatUrl }}"
      vid: CU
      scope: all
      tab: all
    links:
      - label: Advanced search
        href: "{{ bobcatUrl }}/primo-explore/search?vid=CU&mode=advanced"
  - key: primo-cooper
    label: Cooper Library Catalog
    title: Books & e-books, journals & e-journals, videos, and other materials in the Cooper Union Library
    engine:
      type: primo
      institution: CU
      bobcatUrl: "{{ bobcatUrl }}"
      vid: CU
      scope: cu
      tab: cu
    links:
      - label: Advanced search
        href: "{{ bobcatUrl }}/primo-explore/search?vid=CU&mode=advanced"
  - key: reserves
    <<: *ares-reserves