---
bobcatUrl: &bobcat-url
  http://bobcatdev.library.nyu.edu

default-tabs: &default-tabs
  articles:
    label: Articles & Databases
    title: Search databases for articles or browse databases by subject
    alt: Search databases for articles or browse databases by subject
    href: http://guides.nyu.edu/arch
    target: _blank
  books:
    engine: primo
    label: Books & More
    title: Search NYU's catalog for books, journals, scripts, scores, archival
      materials, NYU dissertations, videos, sound recordings
    alt: Search NYU's catalog for books, journals, scripts, scores, archival materials,
      NYU dissertations, videos, sound recordings
  journals:
    engine: getit
    label: Journals
    title: Search for journals by title or for articles by citation
    alt: Search for journals by title or for articles by citation
  reserves:
    engine: primo
    label: Course Reserves
    title: Search for library materials that are held at one location for a particular course
    alt: Search for library materials that are held at one location for a particular course

default-tab-links: &default-tab-links
  books:
  - label: Advanced search
    href: http://bobcat.library.nyu.edu/primo-explore/search?vid=NYU&mode=advanced
  journals:
  - label: Advanced search
    href: https://getit.library.nyu.edu
  reserves:
  - label: Advanced search
    href: http://bobcat.library.nyu.edu/primo-explore/search?tab=reserves&search_scope=bobstcr&vid=NYU&sortby=rank&lang=en_US

default-getit-search-values: &default-getit-search-values
  journals:
    searchTypes:
    - label: contains
      value: contains
    - label: begins with
      value: begins
    - label: exact match
      value: exact

institutions:
  NYU:
    tabsList:
    - books
    - articles
    - journals
    - reserves
    tabs:
      <<: *default-tabs
    tabLinks:
      <<: *default-tab-links
    primoSearchValues:
      books:
        bobcatUrl: *bobcat-url
        vid: NYU
        scope: all
        tab: all
      reserves:
        bobcatUrl: *bobcat-url
        vid: NYU
        scope: bobstcr
        tab: reserves
    getitSearchValues:
      <<: *default-getit-search-values
  NYUAD:
    tabsList:
    - books
    - articles
    - journals
    - reserves
    - guides
    - accounts
    tabs:
      <<: *default-tabs
      guides:
        label: Subject Guides
        title: Subject Guides
        alt: Subject Guides
        placeholder: Enter Search Words (e.g. Company research)
      
