---
articles: &guides-articles
  label: Articles & Databases
  title: Search databases for articles or browse databases by subject
  alt: Search databases for articles or browse databases by subject
  open:
    href: http://guides.nyu.edu/arch
    target: _blank
books: &bobcat-books
  label: Books & More
  title: Search NYU's catalog for books, journals, scripts, scores, archival
    materials, NYU dissertations, videos, sound recordings
  alt: Search NYU's catalog for books, journals, scripts, scores, archival materials,
    NYU dissertations, videos, sound recordings
journals: &getit-journals
  label: Journals
  title: Search for journals by title or for articles by citation
  alt: Search for journals by title or for articles by citation
guides: &subject-guides
  label: Subject Guides
  title: Subject Guides
  alt: Subject Guides
accounts: &my-accounts
  label: My Accounts
  title: My Accounts
  alt: My Accounts

getit-engine: &getit-engine
  type: getit
  getitUrl: "{{ getitUrl }}"
  searchTypes:
  - label: contains
    value: contains
  - label: begins with
    value: begins
  - label: exact match
    value: exact

guide-engine: &guide-engine
  type: guide
  guidesUrl: "{{ guidesUrl }}"

ares-reserves: &ares-reserves
  label: Course Reserves
  title: Search for library materials that are held at one location for a particular course
  alt: Search for library materials that are held at one location for a particular course
  open:
    href: https://ares.library.nyu.edu/
    target: _blank

environments:
  production:
    bobcatUrl: http://bobcat.library.nyu.edu
    getitUrl: https://getit.library.nyu.edu/
    guidesUrl: https://guides.nyu.edu/
  staging:
    bobcatUrl: http://bobcatdev.library.nyu.edu
    getitUrl: https://qa.getit.library.nyu.edu/
    guidesUrl: https://guides.nyu.edu/
  development:
    bobcatUrl: http://bobcatdev.library.nyu.edu
    getitUrl: https://qa.getit.library.nyu.edu/
    guidesUrl: https://guides.nyu.edu/

institutions:
  NYU:
  - key: books
    <<: *bobcat-books
    engine:
      type: primo
      institution: NYU
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYU
      scope: all
      tab: all
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?vid=NYU&mode=advanced"
  - key: articles
    <<: *guides-articles
  - key: journals
    <<: *getit-journals
    engine:
      <<: *getit-engine
      institution: NYU
    links:
    - label: Advanced search
      href: "{{ getitUrl }}"
  - key: reserves
    <<: *ares-reserves
  NYUAD:
  - key: books
    <<: *bobcat-books
    engine:
      type: primo
      institution: NYUAD
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYUAD
      scope: all
      tab: all
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?vid=NYUAD&mode=advanced"
  - key: articles
    label: Articles & Databases
    title: Search databases for articles or browse databases by subject
    alt: Search databases for articles or browse databases by subject
    open:
      href: http://guides.nyu.edu/adarch
      target: _blank
  - key: journals
    <<: *getit-journals
    engine:
      <<: *getit-engine
      institution: NYUAD
    links:
    - label: Advanced search
      href: "{{ getitUrl }}/?&umlaut.institution=NYUAD"
  - key: reserves
    label: Course Reserves
    title: Search for library materials that are held at one location for a particular course
    alt: Search for library materials that are held at one location for a particular course
    engine:
      type: primo
      institution: NYUAD
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYUAD
      scope: nyuadcr
      tab: nyuadcr
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?tab=nyuadcr&search_scope=nyuadcr&vid=NYUAD&mode=advanced"
  - key: guides
    <<: *subject-guides
    engine:
      <<: *guide-engine
    links:
    - label: All Subject Guides
      href: https://guides.nyu.edu/
    - label: Abu Dhabi Library Guides
      href: https://guides.nyu.edu/abudhabi
  - key: accounts
    <<: *my-accounts
    links:
    - label: Interlibrary Loan
      href: https://ill.library.nyu.edu/
    - label: Library Account
      href: https://eshelf.library.nyu.edu/account
  NYUSH:
  - key: books
    <<: *bobcat-books
    engine:
      type: primo
      institution: NYUSH
      bobcatUrl: "{{ bobcatUrl }}"
      vid: NYUSH
      scope: all
      tab: all
    links:
    - label: Advanced search
      href: "{{ bobcatUrl }}/primo-explore/search?vid=NYUSH&mode=advanced"
  - key: articles
    <<: *guides-articles
  - key: journals
    <<: *getit-journals
    engine:
      <<: *getit-engine
      institution: NYUSH
    links:
    - label: Advanced search
      href: "{{ getitUrl }}/?&umlaut.institution=NYUSH"
  - key: reserves
    <<: *ares-reserves
  - key: guides
    <<: *subject-guides
    engine:
      <<: *guide-engine
    links:
    - label: All Subject Guides
      href: https://guides.nyu.edu/
    - label: Shanghai Library Guides
      href: https://guides.nyu.edu/?group_id=5748
  - key: accounts
    <<: *my-accounts
    links:
    - label: Interlibrary Loan
      href: https://ill.library.nyu.edu/
    - label: Library Account
      href: https://eshelf.library.nyu.edu/account