version: '3.7'

x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist
    - ./js:/app/js
    - ./css:/app/css
    - ./config.yml:/app/config.yml
    - ./config.js:/app/config.jsd
    - ./webpack.config.js:/app/webpack.config.js
    - ./babel.config.js:/app/babel.config.js

services:
  web-dev:
    build: .
    image: search-embed-build:latest
    depends_on:
      - nginx
    command: yarn build:dev --watch
    environment:
      NODE_ENV: ${VARIABLE:-development}
    << : *default-volumes

  test:
    build:
      context: .
      dockerfile: Dockerfile.ch_test
      args:
        NODE_VERSION: 8
        CHROME_VERSION: 71.0.3578.98-1
        CHROME_RELEASE: stable
    environment:
      CHROME_BIN: google-chrome-stable
    image: search-embed-test:latest
    command: yarn test
    # volumes:
    # - ./karma.conf.js:/app/karma.conf.js
    # << : *default-volumes

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: search-embed-nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html

  webpack:
    build: .
    image: search-embed-build:latest
    command: yarn build:prod
    environment:
      NODE_ENV: ${VARIABLE:-production}
    # << : *default-volumes