version: '3.7'

x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist
    - ./js:/app/js
    - ./css:/app/css
    - ./config.yml:/app/config.yml
    - ./webpack.config.js:/app/webpack.config.js
    - ./.babelrc:/app/.babelrc

services:
  dev:
    build: .
    image: search-embed-build:latest
    depends_on:
      - nginx
    command: yarn build:dev --watch
    environment:
      NODE_ENV:
    # << : *default-volumes

  test:
    # privileged: true
    build:
      context: .
      dockerfile: Dockerfile.ch_test
    environment:
      CHROME_BIN: google-chrome-unstable
    image: search-embed-test:latest
    command: yarn test
    # << : *default-volumes

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: search-embed-nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html

  webpack_production:
    build: .
    image: search-embed-build:latest
    command: yarn build:prod
    # << : *default-volumes

  webpack_staging:
    build: .
    image: search-embed-build:latest
    command: yarn build:staging
    # << : *default-volumes