version: '3.7'
services:
  dev:
    build: .
    image: search-embed-build:latest
    depends_on:
      - nginx
    command: yarn build:dev --watch
    volumes:
      - ./dist:/app/dist
      - ./js:/app/js
      - ./css:/app/css
      - ./config.yml:/app/config.yml

  webpack_prod:
    build: .
    image: search-embed-build:latest
    command: yarn build
    volumes:
    # - ./dist:/app/dist

  webpack_dev:
    build: .
    image: search-embed-build:latest
    command: yarn build:dev
    volumes:
    # - ./dist:/app/dist

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: search-embed-nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html

  deploy-s3-dev:
    build:
      context: .
      dockerfile: Dockerfile.aws
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    command: aws s3 sync app/dist/ s3://cdn-dev.library.nyu.edu/bess-vue
    volumes:
    - ./dist:/app/dist
