x-volumes: &default-volumes
  volumes:
    - ./js:/app/js
    - ./css:/app/css
    - ./dist:/app/dist

version: '3.7'
services:

  dev:
    build: .
    image: search-embed-build:latest
    depends_on:
      - build
      - nginx
    command: yarn build:dev --watch
    <<: *default-volumes

  build:
    build: .
    image: search-embed-build:latest
    <<: *default-volumes
    command: yarn build

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: search-embed-nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html
