version: '3'
services:

  dev:
    image: search-embed-build:latest
    depends_on:
      - build
      - nginx
    command: yarn build:dev --watch
    volumes:
      - .:/app

  build:
    build: .
    image: search-embed-build:latest
    volumes:
      - .:/app
    command: yarn build

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: search-embed-nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/usr/share/nginx/html
