version: '3.9'

x-default-volumes: &default-volumes
  volumes:
    - ./config:/app/config
    - ./dist:/app/dist
    - ./src:/app/src

x-build: &x-build
  image: bess-vue-build
  build:
    context: ./
    cache_from:
      - bess-vue-build
    dockerfile: Dockerfile

x-dev: &x-dev
  image: bess-vue-dev
  ports:
    - "5173:5173"
  build:
    context: ./
    cache_from:
      - bess-vue-dev
    dockerfile: Dockerfile

services:
  build-dev:
    <<: *x-build
    #    <<: [ *x-build, *default-volumes ]
    command: npm run build:dev

  build-dev-watch:
    <<: *x-build
    #    <<: [ *x-build, *default-volumes ]
    command: npm run build:dev:watch

  build-prod:
    <<: *x-build
#    <<: [ *x-build, *default-volumes ]
    command: npm run build:prod

  build-prod-watch:
    <<: *x-build
    #    <<: [ *x-build, *default-volumes ]
    command: npm run build:prod:watch

  dev-nyu:
    <<: *x-dev
#    <<: [ *x-dev, *default-volumes ]
    command: npm run dev:nyu

  dev-nyuad:
    <<: *x-dev
#    <<: [ *x-dev, *default-volumes ]
    command: npm run dev:nyuad

  dev-nyush:
    <<: *x-dev
#    <<: [ *x-dev, *default-volumes ]
    command: npm run dev:nyush

  dev-nyu-home:
    <<: *x-dev
#    <<: [ *x-dev, *default-volumes ]
    command: npm run dev:nyu-home

  eslint-fix:
    <<: *x-build
#    <<: [ *x-build, *default-volumes ]
    command: npm run eslint:fix

  test:
    <<: *x-build
#    <<: [ *x-build, *default-volumes ]
    command: npm run test

  test-update-snapshots:
    <<: [ *x-build, *default-volumes ]
    command: npm run test:update-snapshots
