import { fileURLToPath } from 'node:url';

import { includeIgnoreFile } from '@eslint/compat';
import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import pluginVue from 'eslint-plugin-vue';
import stylistic from '@stylistic/eslint-plugin';
import globals from 'globals';

const gitignorePath = fileURLToPath( new URL( '.gitignore', import.meta.url ) );

export default defineConfig( [
    includeIgnoreFile( gitignorePath, 'Imported .gitignore patterns' ),
    globalIgnores( [ 'browser-overrides/**' ] ),

    js.configs.recommended,
    ...pluginVue.configs['flat/recommended'],
    {
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType : 'module',

            globals: {
                ...globals.browser,
                ...globals.node,
            },
        },

        plugins: {
            '@stylistic': stylistic,
        },

        rules: {
            /* eslint-disable @stylistic/max-len, vue/max-len */

            // Generated by `npm init quasar@latest` when making the eslint
            // config file in another project.  They look useful.
            'prefer-promise-reject-errors': 'off',
            // Allow debugger during development only
            'no-debugger'                 : process.env.NODE_ENV === 'production' ? 'error' : 'off',

            // ESLint Stylistic only
            '@stylistic/indent': [ 'error', 4 ],
            '@stylistic/quotes': [ 'error', 'single' ],
            '@stylistic/semi'  : [ 'error', 'always' ],

            // Shared with Vue
            '@stylistic/array-bracket-newline'  : [ 'error', 'consistent' ],
            '@stylistic/array-bracket-spacing'  : [ 'error', 'always' ],
            '@stylistic/array-element-newline'  : [ 'error', 'consistent' ],
            '@stylistic/arrow-spacing'          : [ 'error', { 'before': true, 'after': true } ],
            '@stylistic/block-spacing'          : [ 'error', 'always' ],
            '@stylistic/brace-style'            : [ 'error', '1tbs' ],
            '@stylistic/comma-dangle'           : [ 'error', 'always-multiline' ],
            '@stylistic/comma-spacing'          : [ 'error', { 'before': false, 'after': true } ],
            '@stylistic/comma-style'            : [ 'error', 'last' ],
            '@stylistic/computed-property-spacing' : [ 'error', 'always' ],
            '@stylistic/dot-location'           : [ 'error', 'property' ],
            '@stylistic/function-call-spacing'  : [ 'error', 'never' ],
            '@stylistic/key-spacing'            : [ 'error', { align: 'colon' } ],
            '@stylistic/keyword-spacing'        : [ 'error', { before: true } ],
            '@stylistic/max-len'                : [ 'warn', { code: 80, tabWidth: 4 } ],
            '@stylistic/multiline-ternary'      : [ 'error', 'always-multiline' ],
            '@stylistic/no-extra-parens'        : [ 'error', 'all' ],
            '@stylistic/object-curly-newline'   : [ 'error', { multiline: true, consistent: true } ],
            '@stylistic/object-curly-spacing'   : [ 'error', 'always' ],
            '@stylistic/object-property-newline': [ 'error', { allowAllPropertiesOnSameLine: true } ],
            '@stylistic/operator-linebreak'     : [ 'error', 'after' ],
            '@stylistic/space-in-parens'        : [ 'error', 'always' ],
            '@stylistic/space-infix-ops'        : [ 'error' ],
            '@stylistic/space-unary-ops'        : [ 'error', { words: true, nonwords: false } ],
            '@stylistic/template-curly-spacing' : [ 'error', 'always' ],

            // Vue only
            'vue/block-tag-newline': [
                'error',
                {
                    'singleline': 'never',
                    'multiline' : 'always',
                },
            ],
            'vue/script-indent': [ 'error', 4 ],

            // Shared with ESlint Stylistic
            'vue/array-bracket-newline'        : [ 'error', 'consistent' ],
            'vue/array-bracket-spacing'        : [ 'error', 'always' ],
            'vue/array-element-newline'        : [ 'error', 'consistent' ],
            'vue/arrow-spacing'                : [ 'error', { 'before': true, 'after': true } ],
            'vue/block-spacing'                : [ 'error', 'always' ],
            'vue/brace-style'                  : [ 'error', '1tbs' ],
            'vue/comma-dangle'                 : [ 'error', 'always-multiline' ],
            'vue/comma-spacing'                : [ 'error', { 'before': false, 'after': true } ],
            'vue/comma-style'                  : [ 'error', 'last' ],
            'vue/dot-location'                 : [ 'error', 'property' ],
            'vue/func-call-spacing'            : [ 'error', 'never' ],
            'vue/key-spacing'                  : [ 'error', { align: 'colon' } ],
            'vue/keyword-spacing'              : [ 'error', { before: true } ],
            'vue/max-len'                      : [ 'warn', { code: 80, tabWidth: 4 } ],
            'vue/multiline-ternary'            : [ 'error', 'always-multiline' ],
            'vue/no-extra-parens'              : [ 'error', 'all' ],
            'vue/no-required-prop-with-default': [ 'error', { 'autofix': false } ],
            'vue/object-curly-newline'         : [ 'error', { multiline: true, consistent: true } ],
            'vue/object-curly-spacing'         : [ 'error', 'always' ],
            'vue/object-property-newline'      : [ 'error', { allowAllPropertiesOnSameLine: true } ],
            'vue/operator-linebreak'           : [ 'error', 'after' ],
            'vue/space-in-parens'              : [ 'error', 'always' ],
            'vue/space-infix-ops'              : [ 'error' ],
            'vue/space-unary-ops'              : [ 'error', { words: true, nonwords: false } ],
            'vue/template-curly-spacing'       : [ 'error', 'always' ],

            /* eslint-enable @stylistic/max-len, vue/max-len */
        },
    },
] );
