docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app

test: &test
  run:
    name: Test
    command: |
      docker-compose run test

deploy: &deploy
  run:
    name: Deploys to AWS
    command: |
      AWS_ACCESS_KEY_ID=$WEB_CDN_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$WEB_CDN_AWS_SECRET_ACCESS_KEY aws s3 sync ~/app/dist/ $S3_URI/bess-vue

version: 2
jobs:
  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *test
      - run:
          name: Webpack
          command: |
            NODE_ENV=staging docker-compose run webpack
      - run:
          name: Copies webpack output
          command: |
            docker cp $(docker ps -a -q --filter name=webpack):/app/dist/ .
      - *deploy
  deploy-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *test
      - run:
          name: Webpack
          command: |
            NODE_ENV=production docker-compose run webpack
      - run:
          name: Copies webpack output
          command: |
            docker cp $(docker ps -a -q --filter name=webpack):/app/dist/ .
      - *deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: master
