docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
  working_directory: ~/app

test: &test
  run:
    name: Test
    command: |
      docker-compose run test

deploy: &deploy
  run:
    name: Deploys to AWS
    command: |
      AWS_ACCESS_KEY_ID=$WEB_CDN_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$WEB_CDN_AWS_SECRET_ACCESS_KEY aws s3 sync ~/app/dist/ s3://cdn-dev.library.nyu.edu/bess-vue

version: 2
jobs:
  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *test
      - run:
          name: Webpacks
          command: |
            docker-compose run webpack_staging
      - run:
          name: Copies webpack output
          command: |
            docker cp $(docker ps -a -q --filter name=webpack_staging):/app/dist/ .
      - *deploy
  deploy-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *test
      - run:
          name: Webpacks
          command: |
            docker-compose run webpack_production
      - run:
          name: Copies webpack output
          command: |
            docker cp $(docker ps -a -q --filter name=webpack_production):/app/dist/ .
      - *deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: master
