docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
  working_directory: ~/app

test: &test
  run:
    name: Test
    command: |
      docker-compose run test

s3_deploy: &s3_deploy
  aws-s3/sync:
    from: assets
    to: '${S3_URI}/bess-vue'
    aws-access-key-id: WEB_CDN_AWS_ACCESS_KEY_ID
    aws-secret-access-key: WEB_CDN_AWS_SECRET_ACCESS_KEY
    arguments: |
      --include "dist" \
      --include "example-htmls" \
      --delete
    overwrite: true

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *test
      - run:
          name: Webpack
          command: |
            NODE_ENV=staging docker-compose run webpack
      - run:
          name: Copies webpack output
          command: |
            docker cp $(docker ps -a -q --filter name=webpack):/app/dist/ .
      - *s3_deploy
      - store_artifacts:
          path: dist

  deploy-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - *test
      - run:
          name: Webpack
          command: |
            NODE_ENV=production docker-compose run webpack
      - run:
          name: Copies webpack output
          command: |
            docker cp $(docker ps -a -q --filter name=webpack):/app/dist/ .
      - *s3_deploy
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: master
